
import React from 'react';
import { LayoutDashboard, Sprout, CloudSun, Bug, Droplets, TrendingUp, MessageSquare, Users, Settings, ShieldCheck } from 'lucide-react';

export const TRANSLATIONS = {
  sw: {
    app_name: 'Nasafari Mkulima',
    dashboard: 'Dashibodi',
    my_farm: 'Shamba Langu',
    weather: 'Hali ya Hewa',
    pest_scanner: 'Scanner ya Wadudu',
    irrigation: 'Umwagiliaji',
    market: 'Soko',
    ai_chat: 'Msaidizi wa AI',
    community: 'Jamii & Mafunzo',
    settings: 'Mipangilio',
    admin: 'Usimamizi',
    welcome: 'Karibu Tena',
    alerts: 'Tahadhari',
    market_highlights: 'Bei za Soko',
    crop_status: 'Hali ya Mazao',
    ask_ai: 'Uliza kwa sauti',
    planting_date: 'Tarehe ya Kupanda',
    farm_size: 'Ukubwa wa Shamba',
    diagnosis: 'Utambuzi',
    treatment: 'Matibabu',
    confidence: 'Uhakika wa AI',
    share: 'Shiriki Habari',
    why_advice: 'Kwanini ushauri huu?',
    crop_research: 'Utafiti wa Mazao',
    vision: 'Dira Yetu',
    mission: 'Dhima Yetu',
    core_values: 'Maadili Yetu',
    objectives: 'Malengo',
    login: 'Ingia',
    signup: 'Jisajili',
    experts: 'Wataalamu wetu',
    copyright: '© 2026 Nasafari Foundation. Haki zote zimehifadhiwa.',
    website: 'www.naskilimo.com',
    email: 'support@naskilimo.com',
    phone: '+255 713 968 004',
    office: 'Kihesa, Iringa, Tanzania'
  },
  en: {
    app_name: 'Nasafari Mkulima',
    dashboard: 'Dashboard',
    my_farm: 'My Farm',
    weather: 'Weather',
    pest_scanner: 'Pest Scanner',
    irrigation: 'Irrigation',
    market: 'Market Intel',
    ai_chat: 'AI Assistant',
    community: 'Community & Learning',
    settings: 'Settings',
    admin: 'Admin Panel',
    welcome: 'Welcome Back',
    alerts: 'Alerts',
    market_highlights: 'Market Prices',
    crop_status: 'Crop Status',
    ask_ai: 'Ask with voice',
    planting_date: 'Planting Date',
    farm_size: 'Farm Size',
    diagnosis: 'Diagnosis',
    treatment: 'Treatment',
    confidence: 'AI Confidence',
    share: 'Share Info',
    why_advice: 'Why this advice?',
    crop_research: 'Crop Research',
    vision: 'Our Vision',
    mission: 'Our Mission',
    core_values: 'Core Values',
    objectives: 'Objectives',
    login: 'Login',
    signup: 'Sign Up',
    experts: 'Our Experts',
    copyright: '© 2026 Nasafari Foundation. All Rights Reserved.',
    website: 'www.naskilimo.com',
    email: 'support@naskilimo.com',
    phone: '+255 713 968 004',
    office: 'Kihesa, Iringa, Tanzania'
  }
};

export const NAV_ITEMS = [
  { id: 'dashboard', icon: <LayoutDashboard size={20} />, labelSw: 'Dashibodi', labelEn: 'Dashboard' },
  { id: 'myfarm', icon: <Sprout size={20} />, labelSw: 'Shamba Langu', labelEn: 'My Farm' },
  { id: 'weather', icon: <CloudSun size={20} />, labelSw: 'Hali ya Hewa', labelEn: 'Weather' },
  { id: 'pest', icon: <Bug size={20} />, labelSw: 'Scanner', labelEn: 'Scanner' },
  { id: 'market', icon: <TrendingUp size={20} />, labelSw: 'Soko', labelEn: 'Market' },
  { id: 'chat', icon: <MessageSquare size={20} />, labelSw: 'AI Chat', labelEn: 'AI Chat' },
  { id: 'community', icon: <Users size={20} />, labelSw: 'Jamii', labelEn: 'Community' },
  { id: 'admin', icon: <ShieldCheck size={20} />, labelSw: 'Usimamizi', labelEn: 'Admin', adminOnly: true },
  { id: 'settings', icon: <Settings size={20} />, labelSw: 'Mipangilio', labelEn: 'Settings' }
];
